### ISSUE TITLE
Grab energy readings from my smart meter

### ISSUE THREAD

**Issue by Norien** [Norien/Home-Assistant-Config#42]
http://diy-ha.com/track-realtime-electrical-use/

**Comment by Norien** [comment]
nope won't work it's too old

```
Traceback (most recent call last):
  File "bidgely.py", line 22, in <module>
    br.open("https://www.bidgely.com/user/login")
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_mechanize.py", line 25                                                 4, in open
    return self._mech_open(url_or_request, data, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_mechanize.py", line 31                                                 0, in _mech_open
    raise response
mechanize._response.httperror_seek_wrapper: HTTP Error 403: request disallowed by robots.txt
homeserver@homeserver:/home/homeassistant/.homeassistant/shell$ HTTP Error 403: request disallowed by robots.txt
```

**Comment by Norien** [comment]
quite a bit over my head at this point. Hard to as for help as it's all very personal location based account stuff. maybe will look into this later
