### ISSUE TITLE
Setup new sensor for internet usage

### ISSUE THREAD

**Issue by Norien** [Norien/Home-Assistant-Config#58]
- https://github.com/robmathers/rogersusage

**Comment by Norien** [comment]
getting some errors possibly related to requests package?
```
(homeassistant) homeassistant@homeserver:/home/homeserver$ python2 /home/homeassistant/.homeassistant/shell/rogersusage.py
Login ID: xxxXXxx@gmail.com
Password:
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/shell/rogersusage.py", line 227, in <module>
    main()
  File "/home/homeassistant/.homeassistant/shell/rogersusage.py", line 201, in main
    login_cookies = login(username, password)
  File "/home/homeassistant/.homeassistant/shell/rogersusage.py", line 29, in login
    url=response.next.url,
AttributeError: 'Response' object has no attribute 'next'

```
I contacted the author of the rogersusage.py script and he fixed it so older request work!

**Comment by Norien** [comment]
Working great now!

![internet_usage](https://cloud.githubusercontent.com/assets/8930713/26680254/b58d3868-46a6-11e7-91f4-b9830e88381c.PNG)
```
sensor:
  - platform: command_line
    command: "python /home/homeassistant/.homeassistant/shell/rogersusage.py --l=xxXXXxx@gmail.com --p=PASSWORD --csv"
    name: 'usage'
    scan_interval: 86400

  - platform: template
    sensors:
      usage_downloaded:
        value_template: "{{states.sensor.usage.state.split(',')[0]}}"
        unit_of_measurement: "GB"
  - platform: template
    sensors:
      usage_uploaded:
        value_template: "{{states.sensor.usage.state.split(',')[1]}}"
        unit_of_measurement: "GB"
  - platform: template
    sensors:
      usage_total_usage:
        value_template: "{{states.sensor.usage.state.split(',')[2]}}"
        unit_of_measurement: "GB"
  - platform: template
    sensors:
      usage_usage_cap:
        value_template: "{{states.sensor.usage.state.split(',')[3]}}"
        unit_of_measurement: "GB"
  - platform: template
    sensors:
      usage_remaining_usage:
        value_template: "{{states.sensor.usage.state.split(',')[4]}}"
        unit_of_measurement: "GB"
```
